ecommerce/coupons/urls.py
from django.conf.urls import url

from ecommerce.coupons import views

urlpatterns = [
    url(r'^offer/$', views.CouponOfferView.as_view(), name='offer'),
    url(r'^redeem/$', views.CouponRedeemView.as_view(), name='redeem'),
    url(
        r'^enrollment_code_csv/(?P<number>[-\w]+)/$',
        views.EnrollmentCodeCsvView.as_view(),
        name='enrollment_code_csv'
    ),
    url(r'^(.*)$', views.CouponAppView.as_view(), name='app'),
]

ecommerce/courses/urls.py
from django.conf.urls import url

from ecommerce.courses import views

urlpatterns = [
    url(r'^migrate/$', views.CourseMigrationView.as_view(), name='migrate'),
    url(r'^convert_course/$', views.ConvertCourseView.as_view(), name='convert_course'),

    # Declare all paths above this line to avoid dropping into the Course Admin Tool (which does its own routing)
    url(r'^(.*)$', views.CourseAppView.as_view(), name='app'),
]

ecommerce/credit/urls.py
from django.conf.urls import url

from ecommerce.core.constants import COURSE_ID_PATTERN
from ecommerce.credit.views import Checkout

urlpatterns = [
    url(r'^checkout/{course}/$'.format(course=COURSE_ID_PATTERN),
        Checkout.as_view(), name='checkout'),
]

ecommerce/urls.py
import os

from auth_backends.urls import auth_urlpatterns
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.utils.translation import ugettext_lazy as _
from django.views.defaults import page_not_found, server_error
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog
from rest_framework_swagger.views import get_swagger_view

from ecommerce.core import views as core_views
from ecommerce.core.url_utils import get_lms_dashboard_url
from ecommerce.core.views import LogoutView
from ecommerce.extensions.payment.views.apple_pay import ApplePayMerchantDomainAssociationView
from ecommerce.extensions.urls import urlpatterns as extensions_patterns


def handler403(_):
    """Redirect unauthorized users to the LMS student dashboard.

    Removing URLs isn't the most elegant way to hide Oscar's front-end from
    public view. It would require revising templates and parts of the Oscar core
    which assume that these URLs exist. However, a clean way to, in effect,
    disable these URLs is to only make them available to users with staff
    permissions, the same protection used to guard the management dashboard from
    public access.

    This minimally invasive approach allows us to protect Oscar's front-end
    without sacrificing any internal functionality. Users not authorized to view
    Oscar's front-end are redirected to the LMS student dashboard, as one would
    usually be after signing into the LMS.
    """
    return redirect(get_lms_dashboard_url())


admin.autodiscover()
admin.site.site_header = _('E-Commerce Service Administration')
admin.site.site_title = admin.site.site_header

# NOTE 1: Add our logout override first to ensure it is registered by Django as the actual logout view.
# NOTE 2: These same patterns are used for rest_framework's browseable API authentication links.
AUTH_URLS = [url(r'^logout/$', LogoutView.as_view(), name='logout'), ] + auth_urlpatterns

WELL_KNOWN_URLS = [
    url(r'^.well-known/apple-developer-merchantid-domain-association.txt$',
        ApplePayMerchantDomainAssociationView.as_view(), name='apple_pay_domain_association'),
]

urlpatterns = AUTH_URLS + WELL_KNOWN_URLS + [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auto_auth/$', core_views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^api-auth/', include(AUTH_URLS, namespace='rest_framework')),
    url(r'^api-docs/', get_swagger_view(title='Ecommerce API'), name='api_docs'),
    url(r'^courses/', include('ecommerce.courses.urls', namespace='courses')),
    url(r'^credit/', include('ecommerce.credit.urls', namespace='credit')),
    url(r'^coupons/', include('ecommerce.coupons.urls', namespace='coupons')),
    url(r'^health/$', core_views.health, name='health'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['courses']), name='javascript-catalog'),
    url(r'^management/', include('ecommerce.management.urls', namespace='management')),
    url(r'^programs/', include('ecommerce.programs.urls', namespace='programs')),
    url(r'^enterprise/', include('ecommerce.enterprise.urls', namespace='enterprise')),
    url(r'^journals/', include('ecommerce.journals.urls', namespace='journals')),  # TODO: journals dependency
]

# Install Oscar extension URLs
urlpatterns += extensions_patterns

robots = TemplateView.as_view(template_name='robots.txt', content_type='text/plain')
urlpatterns += [
    url(r'^robots\.txt$', robots, name='robots')
]

if settings.DEBUG and settings.MEDIA_ROOT:  # pragma: no cover
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:  # pragma: no cover
    urlpatterns += [
        url(r'^403/$', handler403, name='403'),
        url(r'^404/$', page_not_found, name='404'),
        url(r'^500/$', server_error, name='500'),
        url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap-demo.html')),
    ]
    # Allow error pages to be tested

    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar  # pylint: disable=import-error, wrong-import-position,wrong-import-order

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls))
        ]

ecommerce/extensions/analytics/models.py
from oscar.apps.analytics.models import *  # pragma: no cover pylint: disable=wildcard-import,unused-wildcard-import

ecommerce/extensions/catalogue/models.py
from django.db import models
from django.db.models.signals import post_init, post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from oscar.apps.catalogue.abstract_models import AbstractProduct

from ecommerce.core.constants import (
    COUPON_PRODUCT_CLASS_NAME,
    COURSE_ENTITLEMENT_PRODUCT_CLASS_NAME,
    ENROLLMENT_CODE_PRODUCT_CLASS_NAME,
    SEAT_PRODUCT_CLASS_NAME
)
from ecommerce.core.utils import log_message_and_raise_validation_error
from ecommerce.journals.constants import JOURNAL_PRODUCT_CLASS_NAME  # TODO: journals dependency


class Product(AbstractProduct):
    course = models.ForeignKey(
        'courses.Course', null=True, blank=True, related_name='products', on_delete=models.CASCADE
    )
    expires = models.DateTimeField(null=True, blank=True,
                                   help_text=_('Last date/time on which this product can be purchased.'))
    original_expires = None

    @property
    def is_seat_product(self):
        return self.get_product_class().name == SEAT_PRODUCT_CLASS_NAME

    @property
    def is_enrollment_code_product(self):
        return self.get_product_class().name == ENROLLMENT_CODE_PRODUCT_CLASS_NAME

    @property
    def is_course_entitlement_product(self):
        return self.get_product_class().name == COURSE_ENTITLEMENT_PRODUCT_CLASS_NAME

    # TODO: journals dependency
    @property
    def is_journal_product(self):
        return self.get_product_class().name == JOURNAL_PRODUCT_CLASS_NAME

    @property
    def is_coupon_product(self):
        return self.get_product_class().name == COUPON_PRODUCT_CLASS_NAME

    def save(self, *args, **kwargs):
        try:
            if not isinstance(self.attr.note, basestring) and self.attr.note is not None:
                log_message_and_raise_validation_error(
                    'Failed to create Product. Product note value must be of type string'
                )
        except AttributeError:
            pass
        super(Product, self).save(*args, **kwargs)  # pylint: disable=bad-super-call


@receiver(post_init, sender=Product)
def update_original_expires(sender, **kwargs):  # pylint: disable=unused-argument
    """Updates original_expires value of an instance.

    The original_expires value is used to save a database call when updating a
    seat's enrollment code expires field.
    """
    instance = kwargs['instance']
    instance.original_expires = instance.expires


@receiver(post_save, sender=Product)
def update_enrollment_code(sender, **kwargs):  # pylint: disable=unused-argument
    """Updates a seat's enrollment code when the seat is updated.

    Whenever a seat's expires field is updated, the enrollment code's expires
    field for that seat needs to be updated in these cases:
        * the enrollment code's expires field was not already set
        * the enrollment code's expires field was set and is not less than the
          seat's one (if it is less that means the enrollment code was
          deactivated manually, in which case it cannot be activated again
          automatically here)
    """
    instance = kwargs['instance']
    if instance.is_seat_product and (instance.expires != instance.original_expires):
        enrollment_code = instance.course.get_enrollment_code()
        if enrollment_code and (enrollment_code.expires is None or enrollment_code.expires >= instance.expires):
            enrollment_code.expires = instance.expires
            enrollment_code.save()
        instance.original_expires = instance.expires


class Catalog(models.Model):
    name = models.CharField(max_length=255)
    partner = models.ForeignKey('partner.Partner', related_name='catalogs', on_delete=models.CASCADE)
    stock_records = models.ManyToManyField('partner.StockRecord', blank=True, related_name='catalogs')

    def __unicode__(self):
        return u'{id}: {partner_code}-{catalog_name}'.format(
            id=self.id,
            partner_code=self.partner.short_code,
            catalog_name=self.name
        )

from oscar.apps.catalogue.models import *  # noqa isort:skip pylint: disable=wildcard-import,unused-wildcard-import,wrong-import-position,wrong-import-order,ungrouped-imports

ecommerce/extensions/checkout/models.py
# noinspection PyUnresolvedReferences
# pylint: disable=wildcard-import
from oscar.apps.checkout.models import *  # pragma: no cover

ecommerce/extensions/customer/models.py
# noinspection PyUnresolvedReferences
from oscar.apps.customer.models import *  # pragma: no cover noqa pylint: disable=wildcard-import,unused-wildcard-import

ecommerce/extensions/dashboard/models.py
# noinspection PyUnresolvedReferences
from oscar.apps.dashboard.models import *  # pragma: no cover noqa pylint: disable=wildcard-import,unused-wildcard-import

ecommerce/enterprise/forms.py
# -*- coding: utf-8 -*-
# TODO: Refactor this to consolidate it with `ecommerce.programs.forms`.
from django import forms
from django.forms.utils import ErrorList
from django.utils.translation import ugettext_lazy as _
from oscar.core.loading import get_model

from ecommerce.enterprise.conditions import EnterpriseCustomerCondition
from ecommerce.enterprise.constants import BENEFIT_MAP, BENEFIT_TYPE_CHOICES
from ecommerce.enterprise.utils import get_enterprise_customer
from ecommerce.extensions.offer.models import OFFER_PRIORITY_ENTERPRISE
from ecommerce.programs.custom import class_path, create_condition

Benefit = get_model('offer', 'Benefit')
ConditionalOffer = get_model('offer', 'ConditionalOffer')
Range = get_model('offer', 'Range')


class EnterpriseOfferForm(forms.ModelForm):
    enterprise_customer_uuid = forms.UUIDField(required=True, label=_('Enterprise Customer UUID'))
    enterprise_customer_catalog_uuid = forms.UUIDField(required=False, label=_('Enterprise Customer Catalog UUID'))
    benefit_type = forms.ChoiceField(choices=BENEFIT_TYPE_CHOICES, label=_('Discount Type'))
    benefit_value = forms.DecimalField(
        required=True, decimal_places=2, max_digits=12, min_value=0, label=_('Discount Value')
    )

    class Meta(object):
        model = ConditionalOffer
        fields = [
            'enterprise_customer_uuid', 'enterprise_customer_catalog_uuid', 'start_datetime', 'end_datetime',
            'benefit_type', 'benefit_value'
        ]
        help_texts = {
            'end_datetime': '',
        }
        labels = {
            'start_datetime': _('Start Date'),
            'end_datetime': _('End Date'),
        }

    def __init__(self, data=None, files=None, auto_id='id_%s', prefix=None, initial=None, error_class=ErrorList,
                 label_suffix=None, empty_permitted=False, instance=None, request=None):
        initial = initial or {}
        self.request = request
        if instance:
            initial.update({
                'enterprise_customer_uuid': instance.condition.enterprise_customer_uuid,
                'enterprise_customer_catalog_uuid': instance.condition.enterprise_customer_catalog_uuid,
                'benefit_type': instance.benefit.proxy().benefit_class_type,
                'benefit_value': instance.benefit.value,
            })
        super(EnterpriseOfferForm, self).__init__(data, files, auto_id, prefix, initial, error_class, label_suffix,
                                                  empty_permitted, instance)

        date_ui_class = {'class': 'add-pikaday'}
        self.fields['start_datetime'].widget.attrs.update(date_ui_class)
        self.fields['end_datetime'].widget.attrs.update(date_ui_class)

    def clean(self):
        cleaned_data = super(EnterpriseOfferForm, self).clean()

        start_datetime = cleaned_data.get('start_datetime')
        end_datetime = cleaned_data.get('end_datetime')
        enterprise_customer_uuid = cleaned_data.get('enterprise_customer_uuid')
        enterprise_customer_catalog_uuid = cleaned_data.get('enterprise_customer_catalog_uuid')

        if not self.instance.pk and enterprise_customer_uuid and enterprise_customer_catalog_uuid:
            enterprise_offer_exists = ConditionalOffer.objects.filter(
                offer_type=ConditionalOffer.SITE,
                condition__enterprise_customer_uuid=enterprise_customer_uuid,
                condition__enterprise_customer_catalog_uuid=enterprise_customer_catalog_uuid,
            ).exists()

            if enterprise_offer_exists:
                for field in ['enterprise_customer_uuid', 'enterprise_customer_catalog_uuid']:
                    self.add_error(field, _('An offer already exists for this Enterprise & Catalog combination.'))

        if cleaned_data['benefit_type'] == Benefit.PERCENTAGE and cleaned_data.get('benefit_value') > 100:
            self.add_error('benefit_value', _('Percentage discounts cannot be greater than 100%.'))

        if end_datetime and not start_datetime:
            self.add_error('start_datetime', _('A start date must be specified when specifying an end date.'))

        if start_datetime and end_datetime and start_datetime > end_datetime:
            self.add_error('start_datetime', _('The start date must occur before the end date.'))

        return cleaned_data

    def save(self, commit=True):
        enterprise_customer_uuid = self.cleaned_data['enterprise_customer_uuid']
        enterprise_customer_catalog_uuid = self.cleaned_data['enterprise_customer_catalog_uuid']
        site = self.request.site

        enterprise_customer = get_enterprise_customer(site, enterprise_customer_uuid)
        enterprise_customer_name = enterprise_customer['name']

        # Note: the actual name is not displayed like this in the template, so it's safe to use the UUID here.
        # And in fact we have to, because otherwise we face integrity errors since Oscar forces this name to be unique.
        # Truncate 'enterprise_customer_name' to 48 characters so that our complete name with
        # format 'Discount of type {site} provided by {enterprise_name} for {catalog_uuid}. does
        # not exceed the limit of 128 characters for Oscar's 'AbstractConditionalOffer' name.
        offer_name = _(u'Discount of type {} provided by {} for {}.'.format(
            ConditionalOffer.SITE,
            enterprise_customer_name[:48],  # pylint: disable=unsubscriptable-object,
            enterprise_customer_catalog_uuid
        ))

        self.instance.name = offer_name
        self.instance.status = ConditionalOffer.OPEN
        self.instance.offer_type = ConditionalOffer.SITE
        self.instance.max_basket_applications = 1
        self.instance.partner = site.siteconfiguration.partner
        self.instance.priority = OFFER_PRIORITY_ENTERPRISE

        if commit:
            benefit = getattr(self.instance, 'benefit', Benefit())
            benefit.proxy_class = class_path(BENEFIT_MAP[self.cleaned_data['benefit_type']])
            benefit.value = self.cleaned_data['benefit_value']
            benefit.save()
            self.instance.benefit = benefit

            if hasattr(self.instance, 'condition'):
                self.instance.condition.enterprise_customer_uuid = enterprise_customer_uuid
                self.instance.condition.enterprise_customer_name = enterprise_customer_name
                self.instance.condition.enterprise_customer_catalog_uuid = enterprise_customer_catalog_uuid
                self.instance.condition.save()
            else:
                self.instance.condition = create_condition(
                    EnterpriseCustomerCondition,
                    enterprise_customer_uuid=enterprise_customer_uuid,
                    enterprise_customer_name=enterprise_customer_name,
                    enterprise_customer_catalog_uuid=enterprise_customer_catalog_uuid,
                )

        return super(EnterpriseOfferForm, self).save(commit)

ecommerce/extensions/dashboard/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class UserFormMixin(forms.Form):
    """ Mixin for user field filtering. """
    username = forms.CharField(required=False, label=_("Username"))
    email = forms.CharField(required=False, label=_("Email"))

ecommerce/templates/edx/partials/_administration_menu.html
{% load i18n %}

<nav class="administration-navbar">
  <div class="container">
    <a {% if admin == "course" %}class="selected"{% endif %} href="{% url 'courses:app' '' %}">{% trans "Courses" %}</a>
    <a {% if admin == "coupon" %}class="selected"{% endif %} href="{% url 'coupons:app' '' %}">{% trans "Coupons" %}</a>
    <a {% if admin == "program_offers" %}class="selected"{% endif %} href="{% url 'programs:offers:list' %}">
      {% trans "Program Offers" %}
    </a>
    <a {% if admin == "enterprise_offers" %}class="selected"{% endif %} href="{% url 'enterprise:offers:list' %}">
      {% trans "Enterprise Offers" %}
    </a>
    <!-- # TODO: journal dependency -->
    <a {% if admin == "journal_offers" %}class="selected"{% endif %} href="{% url 'journals:offers:list' %}">
      {% trans "Journal Bundle Offers" %}
    </a>
  </div>
</nav>

ecommerce/templates/edx/partials/_base_navbar.html
{% load i18n %}
{% load static %}

<header class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button id="hamburger-button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#main-navbar-collapse" type="button" aria-expanded="false">
        <span class="sr-only">{% trans "Toggle navigation" %}</span>
        <span aria-hidden="true" class="icon-bar"></span>
        <span aria-hidden="true" class="icon-bar"></span>
        <span aria-hidden="true" class="icon-bar"></span>
      </button>
      {% block navbar_brand %}{% endblock navbar_brand %}
    </div>

    <div class="collapse navbar-collapse" id="main-navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li class="btn-group user-menu">
            <button type="button" class="btn btn-default hidden-xs main-btn nav-button"
                    onclick="window.open('{{ lms_dashboard_url }}');">
              <i class="icon fa fa-home" aria-hidden="true"></i>
              <span class="sr-only">{% trans "Dashboard for:" %}</span>
              {{ user.username }}
            </button>
            <button type="button" class="btn btn-default dropdown-toggle hidden-xs nav-button"
                    data-toggle="dropdown"
                    aria-haspopup="true">
              <span class="caret"></span>
              <span class="sr-only">{% trans "Toggle Dropdown" %}</span>
            </button>
            <ul class="dropdown-menu" aria-expanded="false">
              {% block dropdown_menu %}{% endblock dropdown_menu %}
            </ul>
              {% block small_dropdown_menu %}{% endblock small_dropdown_menu %}
          </li>
        {% else %}
          <a class="btn btn-primary navbar-btn hidden-xs" href="{% url 'login' %}">{% trans "Login" %}</a>
          <li class="visible-xs"><a class="nav-link" href="{% url 'login' %}">{% trans "Login" %}</a></li>
          </a>
        {% endif %}
      </ul>
    </div>
  </div>
</header>

ecommerce/templates/edx/partials/_info_message.html
{% if info %}
    <div id="info-message">
        <div class="container">
            <i class="fa fa-info-circle" aria-hidden="true"></i>
            <div class="depth depth message-info-content">
                <h3>{{ info.title }}</h3>
                {{ info.message }}
            </div>
        </div>
    </div>
{% endif %}

ecommerce/templates/edx/partials/_staff_navbar.html
{% extends 'edx/partials/_base_navbar.html' %}
{% load i18n %}
{% load static %}

{% block navbar_brand %}
    {% if admin == "course" %}
        <a class="navbar-brand" href="{% url 'courses:app' '' %}">
            <img class="navbar-brand-logo" alt="{{ platform_name }} logo" src="{% static 'images/default-logo.png' %}"/>
            <div class="navbar-brand-app">{% trans "E-Commerce Course Administration" %}</div>
        </a>
    {% elif admin == "coupon" %}
        <a class="navbar-brand" href="{% url 'coupons:app' '' %}">
            <img class="navbar-brand-logo" alt="{{ platform_name }} logo" src="{% static 'images/default-logo.png' %}"/>
            <div class="navbar-brand-app">{% trans "E-Commerce Coupon Administration" %}</div>
        </a>
    {% elif admin == "program_offers" %}
        <a class="navbar-brand" href="{% url 'programs:offers:list' %}">
            <img class="navbar-brand-logo" alt="{{ platform_name }} logo" src="{% static 'images/default-logo.png' %}"/>
            <div class="navbar-brand-app">{% trans "E-Commerce Program Offers Administration" %}</div>
        </a>
    {% else %}
        <h1 class="navbar-brand">
            <img class="navbar-brand-logo" alt="{{ platform_name }} logo" src="{% static 'images/default-logo.png' %}"/>
        </h1>
    {% endif %}
{% endblock navbar_brand %}

{% block dropdown_menu %}
  {% include "courses/menu_options.html" %}
{% endblock dropdown_menu %}

{% block small_dropdown_menu %}
  {% include "courses/menu_options.html" with additional_class="visible-xs" %}
{% endblock small_dropdown_menu %}

ecommerce/templates/edx/partials/_student_navbar.html
{% extends 'edx/partials/_base_navbar.html' %}
{% load static %}

{% block navbar_brand %}
    <h1 class="navbar-brand">
        <img class="navbar-brand-logo" alt="{{ platform_name }} logo" src="{% static 'images/default-logo.png' %}"/>
    </h1>
{% endblock navbar_brand %}

{% block dropdown_menu %}
  {% include "edx/base_menu.html" %}
{% endblock dropdown_menu %}

{% block small_dropdown_menu %}
  {% include "edx/base_menu.html" with additional_class="visible-xs" %}
{% endblock small_dropdown_menu %}